GET http://localhost:3000/posts

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "authorId": "NULL",
    "create_date": "2022-05-12",
    "title": "loremet dsdsds",
    "content": "Bacon ipsum dolor tenderloin. Salami strip steak biltong, sirloin bacon andouille turkey hamburger pork belly pork chop meatball tenderloin shank ball tip buffalo. Short ribs pancetta turkey buffalo kevin frankfurter venison pork belly brisket chuck turducken beef ribs ham pork chop. "
}

###

PUT http://localhost:3000/posts
Content-Type: application/json

{
    "postId": 1,
    "likes": 1032
}

###

POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "login": "xyz124",
    "password": "123456789"
}

###

POST  http://localhost:3000/user/register
Content-Type: application/json

{
    "login": "xyz124",
    "password": "123456789"
}

###

GET http://localhost:3000/comments?postId=1

###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "userId": 1,
    "postId": 7,
    "content": "xyz123"
}