GET http://localhost:3000/posts

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "authorId": "NULL",
    "create_date": "2022-05-12",
    "title": "loremet rdffegeer",
    "content": "meat fewgfegerhgrtuhjytikryheerfhretherthehrehr meat"
}

###

PUT http://localhost:3000/posts
Content-Type: application/json

{
    "postId": 10,
    "likes": 1032
}

###

POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "login": "xyz124",
    "password": "123456789"
}

###

POST  http://localhost:3000/user/register
Content-Type: application/json

{
    "login": "xyz124",
    "password": "123456789"
}

###

GET http://localhost:3000/comments?postId=1

###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "userId": 1,
    "postId": 7,
    "content": "xyz123"
}